"use strict";

window.STUDIO_HELP = Object.freeze({
  fields: {
    "config.data_dir": {
      title: "Data directory",
      description: "Корневой каталог состояния Runtime: запуски, события, артефакты, approvals, резервные копии Studio и пользовательские сценарии.",
      allowed: "Непустой абсолютный путь или путь внутри домашнего каталога. Каталог должен быть доступен локальному пользователю.",
      example: "~/.gigacode/agent-runtime",
      topic: "runtime",
    },
    "config.max_parallel_agents": {
      title: "Параллельных агентов",
      description: "Глобальный верхний предел одновременно работающих дочерних GigaCode-процессов. DAG и сценарий могут уменьшить, но не увеличить этот предел.",
      allowed: "Целое число от 1.",
      example: "4",
      topic: "runtime",
    },
    "config.default_step_timeout_seconds": {
      title: "Timeout шага",
      description: "Ограничение времени одного agent step, если сценарий не задал собственный timeout_seconds.",
      allowed: "Целое число секунд от 1.",
      example: "900",
      topic: "runtime",
    },
    "config.graceful_cancel_seconds": {
      title: "Graceful cancel",
      description: "Сколько секунд Runtime ждёт штатного завершения дочернего процесса после отмены, прежде чем завершить его принудительно.",
      allowed: "Целое число секунд от 1.",
      example: "10",
      topic: "runtime",
    },
    "config.max_stdout_bytes_per_step": {
      title: "Max stdout",
      description: "Максимальный объём stdout одного шага. Защищает состояние и Web UI от неограниченного вывода модели.",
      allowed: "Целое число от 1024 байт.",
      example: "52428800",
      topic: "runtime",
    },
    "config.max_stderr_bytes_per_step": {
      title: "Max stderr",
      description: "Максимальный объём диагностического stderr одного шага.",
      allowed: "Целое число от 1024 байт.",
      example: "10485760",
      topic: "runtime",
    },
    "config.executable": {
      title: "GigaCode executable",
      description: "Команда или путь к GigaCode CLI, который Runtime запускает для каждого агента.",
      allowed: "Непустая строка. Значение auto включает автоматический поиск установленного GigaCode CLI.",
      example: "auto",
      topic: "runtime",
    },
    "config.model_allowlist": {
      title: "Model allowlist",
      description: "Полный список model ID, которые разрешено указывать агентам сценария. Неизвестная модель отклоняется до запуска.",
      allowed: "Уникальные непустые model ID, по одному на строку.",
      example: "vllm/Qwen3.6-35B-262k",
      topic: "runtime",
      catalog: "models",
    },
    "config.environment_allowlist": {
      title: "Environment allowlist",
      description: "Имена переменных окружения, которые разрешено передавать дочернему GigaCode. Studio никогда не показывает их значения.",
      allowed: "Уникальные имена по шаблону [A-Za-z_][A-Za-z0-9_]*, по одному на строку.",
      example: "PATH\nHOME\nSSL_CERT_FILE",
      topic: "runtime",
    },
    "config.permission_default": {
      title: "Права по умолчанию",
      description: "Базовая политика песочницы Runtime. В сценарии права всё равно задаются отдельно для каждого агента.",
      allowed: "read_only, propose_only, workspace_write или full_access.",
      example: "read_only",
      topic: "permissions",
      catalog: "permissions",
    },
    "config.allow_full_access": {
      title: "Разрешить full access",
      description: "Глобальный аварийный выключатель расширенного режима. Если выключен, ни один сценарий не сможет запустить full_access агента.",
      allowed: "true или false. Для минимальных прав оставьте false.",
      example: "false",
      topic: "permissions",
    },
    "config.require_full_access_confirmation": {
      title: "Требовать подтверждение",
      description: "Переводит full_access запуск в waiting_for_approval до явного approve_run с точным plan_hash.",
      allowed: "true или false. Рекомендуемое корпоративное значение — true.",
      example: "true",
      topic: "permissions",
    },
    "config.max_parallel_full_access_agents": {
      title: "Full access одновременно",
      description: "Отдельный более строгий лимит параллельных агентов с расширенными правами.",
      allowed: "Целое число от 1; не должно превышать общий практический лимит параллельности.",
      example: "1",
      topic: "permissions",
    },
    "config.max_full_access_loop_iterations": {
      title: "Итераций full access loop",
      description: "Защитный предел числа итераций loop, в котором участвует full_access агент.",
      allowed: "Целое число от 1.",
      example: "3",
      topic: "permissions",
    },
    "config.trusted_scenario_name": {
      title: "Имя доверенного сценария",
      description: "Читаемая метка для точного доверенного plan hash. Не является wildcard и не доверяет всем будущим версиям сценария.",
      allowed: "Строчные латинские буквы, цифры, _ и -; первый символ — буква; максимум 64 символа.",
      example: "corporate-readonly-audit",
      topic: "permissions",
    },
    "config.trusted_scenario_hash": {
      title: "Доверенный SHA-256",
      description: "Точный hash скомпилированного плана. Любое изменение inputs, workspace, модели, Skills или конфигурации создаёт другой hash.",
      allowed: "sha256: и ровно 64 строчные шестнадцатеричные цифры.",
      example: "sha256:0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef",
      topic: "permissions",
    },
    "config.web_enabled": {
      title: "Web UI включён",
      description: "Разрешает локальные Dashboard и Runtime Studio. Сервер запускается лениво и не является отдельным daemon.",
      allowed: "true или false.",
      example: "true",
      topic: "runtime",
    },
    "config.web_host": {
      title: "Web UI host",
      description: "Адрес привязки локального Web UI. Ограничен loopback для защиты от публикации Studio в сеть.",
      allowed: "Только 127.0.0.1; поле недоступно для изменения.",
      example: "127.0.0.1",
      topic: "runtime",
    },
    "config.web_port": {
      title: "Web UI port",
      description: "Порт локального сервера. auto выбирает свободный порт при каждом запуске.",
      allowed: "Строка auto или целое число 1024–65535.",
      example: "auto",
      topic: "runtime",
    },
    "config.web_open_automatically": {
      title: "Открывать автоматически",
      description: "Зарезервированная настройка конфигурационного файла. В v1 постоянный автозапуск отключён; браузер открывается по явному /open_studio или CLI --open.",
      allowed: "Только false; поле недоступно для изменения.",
      example: "false",
      topic: "runtime",
    },
    "agent.name": {
      title: "Имя агента",
      description: "Стабильное имя профиля и часть ссылки gigacode:<name>. После создания не переименовывается из формы.",
      allowed: "1–128 символов: латинские буквы, цифры, точка, _ и -; первый символ — буква или цифра.",
      example: "business-analyst-proactive",
      topic: "agents",
    },
    "agent.description": {
      title: "Описание агента",
      description: "Кратко объясняет, когда использовать профиль. Обязательное непустое поле front matter.",
      allowed: "Непустая строка.",
      example: "Проверяет требования, риски и критерии приёмки.",
      topic: "agents",
    },
    "agent.model": {
      title: "Модель агента",
      description: "Подсказка модели в native agent. В сценарии model ID всё равно фиксируется явно, чтобы план оставался воспроизводимым.",
      allowed: "Пусто или model ID из текущего allowlist.",
      example: "vllm/Qwen3.6-35B-262k",
      topic: "agents",
      catalog: "models",
    },
    "agent.approval_mode": {
      title: "Approval mode агента",
      description: "Native GigaCode metadata для прямого вызова профиля. Runtime не наследует это поле и использует permissions сценария; поэтому yolo здесь не включает YOLO в Runtime.",
      allowed: "Пусто, default, plan, auto-edit, yolo или bubble.",
      example: "plan",
      topic: "agents",
      catalog: "approval_modes",
    },
    "agent.color": {
      title: "Цвет агента",
      description: "Необязательная визуальная метка native agent в интерфейсах GigaCode. На выполнение Runtime не влияет.",
      allowed: "Пусто или непустая строка, поддерживаемая вашей версией GigaCode.",
      example: "Purple",
      topic: "agents",
    },
    "agent.tools": {
      title: "Разрешённые tools агента",
      description: "Native allowlist инструментов профиля. Фактический набор дополнительно ограничивается permissions и allowed_tools сценария.",
      allowed: "Уникальные непустые имена tools, по одному на строку.",
      example: "read_file\nsearch_files",
      topic: "agents",
      catalog: "known_tools",
    },
    "agent.disallowed_tools": {
      title: "Запрещённые tools агента",
      description: "Native denylist. Запрет имеет приоритет при построении доступного набора инструментов.",
      allowed: "Уникальные непустые имена tools, по одному на строку.",
      example: "run_shell_command",
      topic: "agents",
      catalog: "known_tools",
    },
    "agent.system_prompt": {
      title: "System prompt агента",
      description: "Основная роль, ограничения, формат результата и правила работы агента. Studio сохранит этот текст как тело Markdown-файла.",
      allowed: "Обязательный непустой UTF-8 текст; полный файл профиля — не более 2 MiB.",
      example: "Ты системный аналитик. Отделяй факты от предположений...",
      topic: "agents",
    },
    "skill.name": {
      title: "Имя Skill",
      description: "Стабильное имя каталога, front matter и ссылки gigacode:<name>.",
      allowed: "1–128 символов: латинские буквы, цифры, точка, _ и -; первый символ — буква или цифра.",
      example: "requirements-review",
      topic: "skills",
    },
    "skill.description": {
      title: "Описание Skill",
      description: "Кратко описывает назначение и момент применения Skill. Используется каталогом GigaCode и Runtime.",
      allowed: "Обязательная непустая строка.",
      example: "Проверяет спецификацию на полноту и тестируемость.",
      topic: "skills",
    },
    "skill.priority": {
      title: "Priority Skill",
      description: "Необязательная числовая metadata GigaCode. Не меняет политику выбора одинаковых Skill в Runtime: user > extension > bundled.",
      allowed: "Пусто или любое конечное число.",
      example: "10",
      topic: "skills",
    },
    "skill.paths": {
      title: "Paths Skill",
      description: "Необязательные glob-подсказки областей файлов, к которым относится Skill.",
      allowed: "Уникальные непустые glob-строки, по одной на строку.",
      example: "src/**/*.py\ntests/**/*.py",
      topic: "skills",
    },
    "skill.user_invocable": {
      title: "User invocable",
      description: "Разрешает пользователю явно вызывать Skill средствами GigaCode.",
      allowed: "true или false.",
      example: "true",
      topic: "skills",
    },
    "skill.disable_model_invocation": {
      title: "Запретить model invocation",
      description: "Запрещает модели самостоятельно выбирать Skill через native GigaCode discovery. Явная передача через skill_refs Runtime остаётся контролируемой сценарием.",
      allowed: "true или false.",
      example: "false",
      topic: "skills",
    },
    "skill.instructions": {
      title: "Инструкции Skill",
      description: "Пошаговый рабочий контракт: когда применять Skill, входы, порядок действий, проверки и ожидаемый результат.",
      allowed: "Обязательный непустой UTF-8 Markdown; полный SKILL.md — не более 2 MiB.",
      example: "# Проверка требований\n\n1. Выдели акторов...",
      topic: "skills",
    },
    "scenario.name": {
      title: "Name сценария",
      description: "Стабильный идентификатор сценария, metadata.name и имя YAML-файла.",
      allowed: "Строчная латинская буква, затем до 63 символов: a-z, 0-9, _ или -.",
      example: "review-repair-loop",
      topic: "scenarios",
    },
    "scenario.title": {
      title: "Title сценария",
      description: "Человекочитаемое название, которое показывается пользователю и в каталоге.",
      allowed: "Непустая строка длиной до 200 символов.",
      example: "Проверка и исправление решения",
      topic: "scenarios",
    },
    "scenario.description": {
      title: "Description сценария",
      description: "Назначение, входные ожидания и границы применения маршрута.",
      allowed: "Пусто или строка до 4000 символов.",
      example: "Создаёт черновик, проверяет его и повторяет исправление до одобрения.",
      topic: "scenarios",
    },
    "scenario.scope": {
      title: "Scope сценария",
      description: "Определяет каталог сохранения и приоритет discovery. Project действует только в текущем workspace; user доступен всем проектам пользователя.",
      allowed: "user или project, если Studio открыта с workspace.",
      example: "project",
      topic: "scenarios",
      catalog: "scenario_scopes",
    },
    "scenario.max_parallel_agents": {
      title: "Max parallel agents сценария",
      description: "Локальный предел параллельности этого DAG. Может только уменьшить глобальный runtime.max_parallel_agents.",
      allowed: "Пусто или целое число от 1.",
      example: "2",
      topic: "execution",
    },
    "scenario.input.name": {
      title: "Ключ input",
      description: "Имя входного значения, доступного в prompt через ${inputs.<name>}.",
      allowed: "Строчная латинская буква, затем до 63 символов: a-z, 0-9, _ или -.",
      example: "task",
      topic: "scenarios",
    },
    "scenario.input.type": {
      title: "Тип input",
      description: "Типизирует вход и используется при schema validation до запуска.",
      allowed: "string, integer, number, boolean, object или array.",
      example: "string",
      topic: "scenarios",
    },
    "scenario.input.default": {
      title: "Default input",
      description: "Значение, используемое при отсутствии входа. JSON разбирается в соответствующий тип; обычный текст остаётся строкой.",
      allowed: "Пусто либо любое JSON-значение или строка, совместимые с выбранным type.",
      example: "\"Проверь спецификацию\"",
      topic: "scenarios",
    },
    "scenario.input.required": {
      title: "Обязательный input",
      description: "Если включено и default отсутствует, Runtime запросит значение через input gate до выполнения.",
      allowed: "true или false.",
      example: "true",
      topic: "scenarios",
    },
    "scenario.input.description": {
      title: "Описание input",
      description: "Поясняет пользователю формат и смысл входного параметра.",
      allowed: "Пусто или строка до 1000 символов.",
      example: "Текст задачи или спецификации для проверки.",
      topic: "scenarios",
    },
    "scenario.agent.alias": {
      title: "Alias агента в сценарии",
      description: "Локальный идентификатор, на который ссылаются agent steps. Не обязан совпадать с reusable agent name.",
      allowed: "Строчная латинская буква, затем до 63 символов: a-z, 0-9, _ или -.",
      example: "reviewer",
      topic: "scenarios",
    },
    "scenario.agent.ref": {
      title: "Reusable agent",
      description: "Выбирает native Markdown-профиль из ~/.gigacode/agents. Его текст и hash фиксируются в ExecutionPlan.",
      allowed: "Пусто для inline prompt или существующая ссылка gigacode:<agent-name> из каталога.",
      example: "gigacode:business-analyst-proactive",
      topic: "agents",
      catalog: "agents",
    },
    "scenario.agent.model": {
      title: "Модель агента сценария",
      description: "Точный model ID дочернего GigaCode-процесса. Обязателен даже при использовании reusable agent.",
      allowed: "Одно значение из текущего model_allowlist.",
      example: "vllm/Qwen3.6-35B-262k",
      topic: "scenarios",
      catalog: "models",
    },
    "scenario.agent.permissions": {
      title: "Permissions агента сценария",
      description: "Фактический уровень доступа этого агента. Skill и native profile не могут его повысить.",
      allowed: "read_only, propose_only, workspace_write или full_access.",
      example: "propose_only",
      topic: "permissions",
      catalog: "permissions",
    },
    "scenario.agent.allowed_tools": {
      title: "Allowed tools сценария",
      description: "Дополнительный allowlist инструментов для этого агента. Итоговый набор пересекается с возможностями permissions и GigaCode CLI.",
      allowed: "Пусто или уникальные непустые имена tools через запятую.",
      example: "read_file, search_files",
      topic: "scenarios",
      catalog: "known_tools",
    },
    "scenario.agent.skill_refs": {
      title: "Skills агента сценария",
      description: "Явный allowlist Skills. Runtime внедряет только выбранные инструкции, фиксирует hashes и блокирует автоматический выбор остальных Skills.",
      allowed: "До 16 уникальных ссылок gigacode:<skill-name> из активного каталога. Cmd/Ctrl выбирает несколько.",
      example: "gigacode:requirements-review",
      topic: "skills",
      catalog: "skills",
    },
    "scenario.agent.system_prompt_file": {
      title: "System prompt file",
      description: "Путь к отдельному prompt-файлу относительно сценария/workspace. Используется только если reusable agent не выбран.",
      allowed: "Пусто или непустой разрешённый локальный путь. Нельзя одновременно задавать reusable agent и inline prompt.",
      example: "prompts/reviewer.md",
      topic: "scenarios",
    },
    "scenario.agent.system_prompt": {
      title: "Inline system prompt",
      description: "Роль агента прямо в YAML сценария. Выберите ровно один источник: reusable agent, prompt file или inline prompt.",
      allowed: "Непустой текст, если два других источника не выбраны.",
      example: "Ты reviewer. Верни только JSON по output_schema.",
      topic: "scenarios",
    },
    "scenario.step.name": {
      title: "ID шага",
      description: "Стабильный идентификатор узла DAG. Используется в needs и выражениях ${steps.<id>.output}.",
      allowed: "Строчная латинская буква, затем до 63 символов: a-z, 0-9, _ или -.",
      example: "review",
      topic: "execution",
    },
    "scenario.step.kind": {
      title: "Kind шага",
      description: "agent запускает один агент; loop последовательно повторяет вложенный DAG до until или защитного предела.",
      allowed: "agent или loop.",
      example: "agent",
      topic: "execution",
    },
    "scenario.step.agent": {
      title: "Agent шага",
      description: "Alias из секции Agents, который выполнит этот agent step.",
      allowed: "Один существующий alias агента текущего сценария.",
      example: "reviewer",
      topic: "execution",
    },
    "scenario.step.needs": {
      title: "Needs",
      description: "Прямые зависимости шага. Шаг стартует только после успешного завершения всех перечисленных узлов.",
      allowed: "Пусто или уникальные ID существующих шагов через запятую; циклы запрещены.",
      example: "draft, security_review",
      topic: "execution",
    },
    "scenario.step.timeout_seconds": {
      title: "Timeout шага",
      description: "Локальное ограничение времени шага. Для agent step пустое значение наследует Runtime default; loop использует общий предел итерационного шага.",
      allowed: "Пусто для agent step либо целое число секунд от 1.",
      example: "900",
      topic: "execution",
    },
    "scenario.step.prompt": {
      title: "Prompt template",
      description: "Задача для шага с безопасными ссылками на inputs, предыдущие outputs, loop и workspace.",
      allowed: "Непустой текст. Поддерживаются ${inputs.name}, ${steps.id.output}, ${loop.iteration}, ${loop.steps.id.output}, ${loop.previous.id.output}, ${run.id}, ${workspace.root}.",
      example: "Проверь результат: ${steps.draft.output}",
      topic: "execution",
    },
    "scenario.step.prompt_file": {
      title: "Prompt template file",
      description: "Внешний UTF-8 шаблон prompt относительно каталога сценария или workspace. Выберите его вместо inline template.",
      allowed: "Пусто либо непустой безопасный локальный путь. Нельзя одновременно задавать template и template_file.",
      example: "review-prompt.txt",
      topic: "execution",
    },
    "scenario.step.context": {
      title: "Prompt context",
      description: "Дополнительный JSON object с именованными данными для шаблона и фиксации в ExecutionPlan.",
      allowed: "Пустой либо валидный JSON object. Массив и скаляр на верхнем уровне запрещены.",
      example: "{\n  \"mode\": \"strict\",\n  \"threshold\": 0.95\n}",
      topic: "execution",
    },
    "scenario.step.output_schema": {
      title: "Output schema",
      description: "JSON Schema структурированного ответа. Runtime не примет результат модели, пока он не соответствует этой схеме.",
      allowed: "JSON object, описывающий ожидаемый результат. Используется, если поле внешнего schema file пусто.",
      example: "{\n  \"type\": \"object\",\n  \"required\": [\"approved\"],\n  \"properties\": {\"approved\": {\"type\": \"boolean\"}}\n}",
      topic: "execution",
    },
    "scenario.step.output_schema_file": {
      title: "Output schema file",
      description: "Внешний файл с JSON Schema относительно каталога сценария или workspace.",
      allowed: "Пусто либо безопасный путь к UTF-8 файлу, содержащему один JSON object. Нельзя одновременно использовать inline schema.",
      example: "review-output.schema",
      topic: "execution",
    },
    "scenario.step.retry_attempts": {
      title: "Retry max attempts",
      description: "Общее число попыток agent step, включая первую. Повторы выполняются только для причин из Retry on.",
      allowed: "Пусто для отсутствия retry либо целое число 1–20.",
      example: "3",
      topic: "execution",
    },
    "scenario.step.retry_backoff": {
      title: "Retry backoff",
      description: "Задержки перед повторными попытками в секундах, последовательно по номеру retry.",
      allowed: "До 19 неотрицательных чисел через запятую.",
      example: "0, 0.5, 2",
      topic: "execution",
    },
    "scenario.step.retry_on": {
      title: "Retry on",
      description: "Классы ошибок, при которых Runtime разрешает повтор шага.",
      allowed: "Уникальные значения: process_error, transient_cli_error, invalid_output, timeout.",
      example: "transient_cli_error, invalid_output, timeout",
      topic: "execution",
    },
    "scenario.condition.ref": {
      title: "Condition ref",
      description: "Выражение, значение которого проверяется перед agent step или в until.",
      allowed: "Пусто для отсутствия when либо допустимая ссылка на input/output/loop/run/workspace.",
      example: "${steps.review.output.approved}",
      topic: "execution",
    },
    "scenario.condition.op": {
      title: "Оператор условия",
      description: "Операция сравнения значения ref с Value. exists проверяет наличие и может не требовать осмысленного Value.",
      allowed: "eq, ne, lt, lte, gt, gte, contains или exists.",
      example: "eq",
      topic: "execution",
    },
    "scenario.condition.value": {
      title: "Значение условия",
      description: "Правая часть сравнения. JSON позволяет задать boolean, number, object или array; обычный текст остаётся строкой.",
      allowed: "Любое JSON-значение или строка.",
      example: "true",
      topic: "execution",
    },
    "scenario.loop.max_iterations": {
      title: "Max iterations",
      description: "Жёсткий предел числа итераций loop. Защищает от бесконечной review/repair цепочки.",
      allowed: "Целое число от 1. Loop обязан иметь max_iterations или timeout_seconds.",
      example: "3",
      topic: "loops",
    },
    "scenario.loop.on_limit": {
      title: "On limit",
      description: "Действие, если until не выполнено до достижения предела.",
      allowed: "fail — завершить ошибкой; pause — ждать решения оператора; best_effort — вернуть лучший накопленный результат.",
      example: "pause",
      topic: "loops",
    },
    "scenario.loop.no_progress_limit": {
      title: "No progress iterations",
      description: "Останавливает loop, если fingerprint результата не меняется указанное число итераций.",
      allowed: "Пусто для отключения либо целое число от 1. При заполнении требуется fingerprint.",
      example: "2",
      topic: "loops",
    },
    "scenario.loop.no_progress_fingerprint": {
      title: "No progress fingerprint",
      description: "Набор выражений, по значениям которых Runtime определяет отсутствие прогресса между итерациями.",
      allowed: "Одно или несколько непустых выражений, по одному на строку.",
      example: "${loop.steps.review.output.feedback}",
      topic: "loops",
    },
    "scenario.loop.until_ref": {
      title: "Until ref",
      description: "Выражение результата текущей итерации, по которому loop решает, завершаться ли.",
      allowed: "Непустая допустимая ссылка, обычно ${loop.steps.<id>.output.<field>}.",
      example: "${loop.steps.review.output.approved}",
      topic: "loops",
    },
    "scenario.loop.until_op": {
      title: "Until operator",
      description: "Оператор проверки условия завершения loop.",
      allowed: "eq, ne, lt, lte, gt, gte, contains или exists.",
      example: "eq",
      topic: "loops",
    },
    "scenario.loop.until_value": {
      title: "Until value",
      description: "Значение, при сравнении с которым loop считается успешно завершённым.",
      allowed: "Любое JSON-значение или строка.",
      example: "true",
      topic: "loops",
    },
    "scenario.result": {
      title: "From expression",
      description: "Определяет общий результат завершённого сценария.",
      allowed: "Непустая допустимая ссылка на output шага, обычно ${steps.<final_step>.output}.",
      example: "${steps.finalize.output}",
      topic: "execution",
    },
  },
  topics: [
    {
      id: "overview",
      title: "Быстрый старт",
      description: "Безопасная последовательность создания рабочей агентской схемы — от Runtime до первого запуска.",
      steps: [
        ["Проверьте Runtime", "В разделе «Настройки» проверьте executable, model allowlist, параллельность, permissions и Web UI. Выполните Preview и Apply, затем переподключите MCP."],
        ["Создайте reusable agents", "В разделе «Агенты» задайте стабильное имя, назначение и подробный system prompt. Профили сохраняются в ~/.gigacode/agents."],
        ["При необходимости создайте Skills", "В разделе «Скиллы» опишите узкую повторяемую процедуру. В сценарии Skill станет доступен агенту только после явного выбора в skill_refs."],
        ["Соберите маршрут", "Создайте inputs, aliases агентов и DAG steps. Независимые steps оставьте без общих needs для параллельного запуска; зависимости задают последовательность."],
        ["Добавьте контракт результата", "Для каждого agent step задайте output_schema, а в Result выберите output финального шага."],
        ["Проверьте до записи", "Preview выполняет production validation и компиляцию плана, показывает target path, hashes и diff. Apply записывает файл атомарно и создаёт backup."],
        ["Запустите через MCP", "Попросите GigaCode сначала показать plan_scenario, затем start_run и дождаться terminal status. Для full_access отдельно проверьте approval gate."],
      ],
      sections: [
        {
          title: "Главное правило",
          paragraphs: ["Studio не запускает сценарий и не меняет уже скомпилированные планы. Она управляет файлами конфигурации, сценариев, agents и Skills для будущих запусков."],
          bullets: ["Сначала создавайте минимальный read_only сценарий.", "Добавляйте параллельность только между независимыми шагами.", "Права расширяйте отдельно для каждого агента.", "Проверяйте diff перед каждым Apply."],
        },
      ],
    },
    {
      id: "examples",
      title: "Полные тестовые примеры",
      description: "Устанавливаемые безопасные объекты, в которых заполнены все поддерживаемые поля Config, Agent, Skill и Scenario.",
      steps: [
        ["Откройте Config", "Активный corporate config содержит все поля рабочей конфигурации. Отдельный schema-valid reference находится в examples/config-all-fields.yaml и включает пример trusted hash."],
        ["Откройте Agent", "Выберите runtime-all-fields-example. В нём заполнены name, description, model, approvalMode, color, tools, disallowedTools и system prompt."],
        ["Откройте Skill", "Выберите runtime-all-fields-example. В нём заполнены priority, paths, user-invocable, disable-model-invocation и инструкции."],
        ["Откройте Scenario", "Выберите corporate-all-fields-example. Он показывает шесть типов inputs, три источника agent prompt, четыре permission mode, prompt/context/schema files, retry, составные conditions, loop/no_progress и result."],
        ["Не запускайте без Preview", "Пример безопасен по prompt и tool allowlist, но намеренно содержит workspace_write и full_access для демонстрации. Full access должен пройти штатный approval gate."],
      ],
      sections: [
        {
          title: "Видимость в GigaCode",
          paragraphs: ["Installer сохраняет пример агента в ~/.gigacode/agents и пример Skill в ~/.gigacode/skills. После перезапуска GigaCode они должны появиться в нативных каталогах; сценарий виден через Agent Runtime."],
          bullets: ["Native approvalMode: yolo относится только к прямому вызову GigaCode agent.", "Runtime не наследует yolo и использует permissions сценария.", "Точные tool ID зависят от сборки GigaCode; пример использует официальные Qwen Code IDs."],
        },
      ],
    },
    {
      id: "runtime",
      title: "Настройки Runtime",
      description: "GigaCode CLI, лимиты исполнения, каталоги состояния и локальный Web UI.",
      steps: [
        ["Выберите data directory", "Оставьте отдельный пользовательский каталог Runtime; не направляйте его в корень проекта или системный каталог."],
        ["Настройте параллельность", "Начните с 2–4 агентов и увеличивайте только после наблюдения за CPU, памятью и квотами моделей."],
        ["Заполните model allowlist", "Копируйте точные model ID из корпоративного GigaCode. Сценарии смогут выбирать только их."],
        ["Ограничьте environment", "Передавайте только необходимые имена переменных. Значения секретов не вводятся в Studio."],
        ["Примените config", "После Apply перезапустите или переподключите MCP, потому что текущий Runtime продолжает работать со старым effective config."],
      ],
      fieldGroups: [
        ["Runtime", ["config.data_dir", "config.max_parallel_agents", "config.default_step_timeout_seconds", "config.graceful_cancel_seconds", "config.max_stdout_bytes_per_step", "config.max_stderr_bytes_per_step"]],
        ["GigaCode CLI", ["config.executable", "config.model_allowlist", "config.environment_allowlist"]],
        ["Web UI", ["config.web_enabled", "config.web_host", "config.web_port", "config.web_open_automatically"]],
      ],
    },
    {
      id: "agents",
      title: "Создание агентов",
      description: "Reusable native agents и их подключение к сценарию через agent_ref.",
      steps: [
        ["Нажмите + в разделе «Агенты»", "Создаётся user profile в ~/.gigacode/agents/<name>.md."],
        ["Опишите назначение", "Description должно отвечать на вопрос «когда выбирать этого агента», а system prompt — «как именно он работает»."],
        ["Ограничьте инструменты", "Не добавляйте tools «на всякий случай». Denylist используйте для явного запрета опасных действий."],
        ["Выполните Preview и Apply", "Studio сформирует YAML front matter и Markdown body, затем проверит профиль тем же parser, который использует Runtime."],
        ["Перезапустите GigaCode", "User profile сохраняется в ~/.gigacode/agents/<name>.md. После перезапуска он должен появиться в native agent catalog и /agents manage."],
        ["Подключите к маршруту", "В Agents сценария выберите Reusable agent. Model и permissions укажите явно: профиль не подменяет контракт исполнения."],
      ],
      fieldGroups: [
        ["Профиль агента", ["agent.name", "agent.description", "agent.model", "agent.approval_mode", "agent.color", "agent.tools", "agent.disallowed_tools", "agent.system_prompt"]],
        ["Агент внутри сценария", ["scenario.agent.alias", "scenario.agent.ref", "scenario.agent.model", "scenario.agent.permissions", "scenario.agent.allowed_tools", "scenario.agent.skill_refs", "scenario.agent.system_prompt_file", "scenario.agent.system_prompt"]],
      ],
      sections: [
        {
          title: "Три источника system prompt",
          paragraphs: ["Для агента сценария выбирается ровно один источник: reusable agent_ref, system_prompt_file или inline system_prompt. Одновременное заполнение нескольких источников отклоняется схемой."],
        },
        {
          title: "YOLO и Runtime",
          paragraphs: ["approvalMode профиля управляет нативным subagent при прямом вызове из GigaCode. Runtime игнорирует это metadata и запускает дочерний CLI по permissions сценария. full_access — не YOLO: он использует auto-edit, явный allowed_tools и отдельный approval gate Runtime."],
        },
      ],
    },
    {
      id: "skills",
      title: "Создание и назначение Skills",
      description: "Офлайн-инструкции GigaCode, явный allowlist и детерминированный выбор источника.",
      steps: [
        ["Создайте узкий Skill", "Один Skill должен описывать одну повторяемую процедуру с понятным условием применения."],
        ["Заполните metadata", "Имя и description обязательны. Paths, priority и invocation flags добавляйте только если они действительно нужны."],
        ["Напишите проверяемые инструкции", "Укажите входы, порядок действий, ограничения, проверки качества и формат результата."],
        ["Сохраните user Skill", "Studio создаст ~/.gigacode/skills/<name>/SKILL.md. Extension и bundled источники доступны только для чтения; для изменения создайте user override."],
        ["Перезапустите GigaCode", "После сохранения user Skill перезапустите GigaCode, чтобы его native catalog и slash commands перечитали ~/.gigacode/skills."],
        ["Назначьте Skill агенту", "В сценарии выберите Skills у конкретного alias. Пустой список не наследует весь пользовательский каталог."],
      ],
      fieldGroups: [
        ["Поля Skill", ["skill.name", "skill.description", "skill.priority", "skill.paths", "skill.user_invocable", "skill.disable_model_invocation", "skill.instructions"]],
        ["Назначение в сценарии", ["scenario.agent.skill_refs", "scenario.agent.permissions"]],
      ],
      sections: [
        {
          title: "Приоритет источников",
          paragraphs: ["При одинаковом name Runtime выбирает user, затем extension, затем bundled. На одном уровне выигрывает канонический каталог с именем Skill, затем лексикографически первый путь."],
          bullets: ["skill_refs не повышает permissions.", "read_only/propose_only используют текст инструкций без scripts и filesystem.", "workspace_write/full_access всё равно ограничиваются фактическими tools и политиками GigaCode."],
        },
      ],
    },
    {
      id: "scenarios",
      title: "Создание сценариев",
      description: "Inputs, agents, DAG steps, структурированные outputs и общий результат.",
      steps: [
        ["Создайте паспорт", "Выберите уникальный name, понятный title и scope. Project подходит для конкретного workspace; user — для повторного использования."],
        ["Опишите inputs", "Добавляйте только данные, которые реально нужны маршруту. Required без default создаёт input gate."],
        ["Добавьте agents", "Каждый alias получает точную модель, permissions и ровно один источник system prompt. Skills выбираются явно."],
        ["Постройте DAG", "Создайте agent steps. Needs определяет зависимости и автоматически формирует последовательные и параллельные waves."],
        ["Задайте output_schema", "Контракт каждого шага должен быть достаточно строгим, чтобы следующий агент мог безопасно использовать output."],
        ["Выберите Result", "Укажите output финального шага. Preview проверит ссылки, зависимости, модели, permissions, agents и Skills."],
      ],
      fieldGroups: [
        ["Паспорт", ["scenario.name", "scenario.title", "scenario.description", "scenario.scope", "scenario.max_parallel_agents"]],
        ["Inputs", ["scenario.input.name", "scenario.input.type", "scenario.input.default", "scenario.input.required", "scenario.input.description"]],
        ["Agents", ["scenario.agent.alias", "scenario.agent.ref", "scenario.agent.model", "scenario.agent.permissions", "scenario.agent.allowed_tools", "scenario.agent.skill_refs", "scenario.agent.system_prompt_file", "scenario.agent.system_prompt"]],
        ["Result", ["scenario.result"]],
      ],
      sections: [
        {
          title: "Schema v1 и расширенные поля",
          paragraphs: ["Неизвестные поля запрещены. Studio редактирует retry, no_progress, prompt context, внешние prompt/schema files и простые conditions. Составные условия all/any/not отображаются как read-preserve блок и сохраняются без изменения."],
        },
      ],
    },
    {
      id: "execution",
      title: "Последовательно и параллельно",
      description: "Как needs превращает шаги сценария в DAG waves.",
      steps: [
        ["Последовательный запуск", "Шаг B получает needs: A, шаг C — needs: B. В каждый момент готов только один узел."],
        ["Параллельный запуск", "Шаги A и B имеют needs: []. Они стартуют в одной wave с учётом лимита параллельности."],
        ["Параллельно-последовательный", "A выполняется первым; B и C зависят от A и идут параллельно; D зависит от B и C и выполняется после обеих ветвей."],
        ["Условный шаг", "when проверяется после завершения needs. Если условие ложно, шаг пропускается по контракту Runtime."],
      ],
      fieldGroups: [
        ["Поля DAG", ["scenario.step.name", "scenario.step.kind", "scenario.step.agent", "scenario.step.needs", "scenario.step.timeout_seconds", "scenario.step.prompt", "scenario.step.prompt_file", "scenario.step.context", "scenario.step.output_schema", "scenario.step.output_schema_file", "scenario.step.retry_attempts", "scenario.step.retry_backoff", "scenario.step.retry_on", "scenario.condition.ref", "scenario.condition.op", "scenario.condition.value", "scenario.result"]],
      ],
      sections: [
        {
          title: "Пример mixed DAG",
          code: "prepare: needs []\nanalysis: needs [prepare]\nreview: needs [prepare]\nfinalize: needs [analysis, review]",
          paragraphs: ["Фактическая параллельность ограничивается меньшим из runtime.max_parallel_agents и scenario.max_parallel_agents."],
        },
      ],
    },
    {
      id: "loops",
      title: "Loops и условия завершения",
      description: "Ограниченные review/repair циклы без бесконечного выполнения.",
      steps: [
        ["Создайте step kind=loop", "Loop содержит собственные вложенные agent steps одной итерации."],
        ["Свяжите вложенные steps", "Например repair использует ${loop.previous.review.output} и затем review проверяет новый результат."],
        ["Настройте until", "Until обычно читает boolean approved из output review текущей итерации."],
        ["Установите предел", "Всегда задавайте небольшой max_iterations и осознанный on_limit. Для full_access действует дополнительный глобальный лимит."],
        ["Проверьте schema outputs", "Поля, на которые ссылается until, должны присутствовать в output_schema соответствующего nested step."],
      ],
      fieldGroups: [
        ["Поля loop", ["scenario.step.needs", "scenario.loop.max_iterations", "scenario.step.timeout_seconds", "scenario.loop.on_limit", "scenario.loop.no_progress_limit", "scenario.loop.no_progress_fingerprint", "scenario.loop.until_ref", "scenario.loop.until_op", "scenario.loop.until_value"]],
      ],
      sections: [
        {
          title: "Выбор on_limit",
          bullets: ["fail — строгий контракт: отсутствие одобрения является ошибкой.", "pause — оператор решает, продолжать ли после достижения предела.", "best_effort — допустим частичный результат; используйте только когда потребитель готов его принять."],
        },
      ],
    },
    {
      id: "permissions",
      title: "Permissions и подтверждения",
      description: "Модель минимальных прав, full_access gates и доверенные plan hashes.",
      steps: [
        ["Начните с read_only", "Для анализа и проверки текста этого обычно достаточно."],
        ["Используйте propose_only для проектов изменений", "Агент формирует рекомендации или патч как результат, но не применяет его."],
        ["Давайте workspace_write точечно", "Только агентам, которым действительно нужно менять файлы внутри workspace."],
        ["Защитите full_access", "Включите глобальный флаг, оставьте confirmation=true и лимит одновременных агентов равным 1."],
        ["Проверяйте plan_hash", "Approval действует только на точный план. Не доверяйте динамическим сценариям через постоянный trusted hash."],
      ],
      fieldGroups: [
        ["Глобальная политика", ["config.permission_default", "config.allow_full_access", "config.require_full_access_confirmation", "config.max_parallel_full_access_agents", "config.max_full_access_loop_iterations", "config.trusted_scenario_name", "config.trusted_scenario_hash"]],
        ["Права агента", ["scenario.agent.permissions", "scenario.agent.allowed_tools", "scenario.agent.skill_refs"]],
      ],
      sections: [
        {
          title: "Значения permissions",
          table: {
            headers: ["Значение", "Назначение"],
            rows: [
              ["read_only", "Анализ без изменения workspace и без tool access."],
              ["propose_only", "Подготовка текста/патча без применения."],
              ["workspace_write", "Изменения внутри workspace через sandbox GigaCode."],
              ["full_access", "Расширенный режим после runtime gates; не обходит TCC, SIP, ACL и корпоративные политики."],
            ],
          },
        },
      ],
    },
    {
      id: "save",
      title: "Preview, Apply и активация",
      description: "Как Studio проверяет и безопасно записывает управляемые файлы.",
      steps: [
        ["Нажмите «Проверить и сохранить»", "Studio отправляет draft на сервер, но ещё ничего не записывает."],
        ["Изучите диагностику", "Используются production parser/schema и компилятор ExecutionPlan, а не упрощённая browser validation."],
        ["Проверьте target и diff", "Убедитесь, что путь, current hash и candidate hash соответствуют ожидаемому ресурсу."],
        ["Нажмите Apply", "Одноразовый preview ID связывается с session; применяются lock, conflict check, backup, atomic replace и post-write validation."],
        ["Активируйте изменение", "Config требует reconnect MCP. Сценарии, agents и Skills попадут в новые планы после обновления каталога; уже идущие runs не меняются."],
      ],
      sections: [
        {
          title: "Что Studio не делает",
          bullets: ["Не записывает секреты environment.", "Не публикует Web UI за пределами 127.0.0.1.", "Не изменяет read-only built-in/extension ресурсы напрямую.", "Не перестраивает уже созданный ExecutionPlan."],
        },
      ],
    },
  ],
});
